name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: 'web/yarn.lock'

    - name: Install dependencies
      working-directory: ./web
      run: yarn install --frozen-lockfile

    - name: Build application
      working-directory: ./web
      run: yarn build

    - name: Run linter
      working-directory: ./web
      run: yarn lint